name: SSH to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH private key
      run: |
        # Save the SSH private key from the GitHub secret
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
        chmod 400 private-key.pem

    - name: Add EC2 instance's SSH host key to known hosts
      run: |
        # Add the EC2 instance to known hosts to avoid SSH warnings
        ssh-keyscan -H ubuntu@ec2-54-152-153-190.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH into EC2
      run: |
        # Connect to EC2 instance using the private key
        ssh -i private-key.pem ec2-user@ubuntu@ec2-54-152-153-190.compute-1.amazonaws.com "echo 'Successfully connected!'"

