name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH with the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Ensure the private key is saved to /tmp/ssh_key with correct permissions
      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      # Test SSH connection (Optional, for debugging)
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.EC2_PUBLIC_IP }}

      # Copy code to EC2
      - name: Copy code to EC2
        run: |
          # Ensure the correct file/directory is passed to scp
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no -r * ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app

      # Restart application on EC2
      - name: Restart application on EC2
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/app
            git pull origin main  # Optional, if using git
            docker compose up -d
          EOF
