name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Run commands on EC2 via SSM
        run: |
          INSTANCE_ID="i-xxxxxxxxxxxxxxxxx"  # Your EC2 instance ID
          DOCUMENT_NAME="AWS-RunShellScript"
          COMMAND="echo 'Hello from GitHub Actions!'"

          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name $DOCUMENT_NAME \
            --parameters 'commands=["$COMMAND"]'
