name: Test SSH Key and Echo Environment Variables

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH private key
      run: |
        # Generate the private key file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem

        # Ensure the key file has the correct permissions
        chmod 400 private-key.pem

    - name: Show environment variables (non-sensitive)
      run: |
        echo "EC2 Host: ${{ secrets.EC2_HOST }}"  # Non-sensitive variable
#
#    - name: Add EC2 instance's SSH host key to known hosts
#      run: |
#        # Add the EC2 instance to known hosts to avoid SSH warnings
#        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into EC2 (without echoing the private key)
      run: |
        # Connect to EC2 instance
        ssh -i private-key.pem ec2-user@${{ secrets.EC2_HOST }} "echo 'Successfully connected!'"
