name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Docker
      run: |
        sudo apt-get update

    - name: Login to AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1  # Adjust region if necessary

    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    - name: Push Docker Image to AWS ECR (Optional, if using ECR)
      run: |
        # Login to ECR (skip if pushing directly to EC2)
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.us-east-1.amazonaws.com
        docker tag fastapi-app:latest <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest
        docker push <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
          docker pull <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d --name fastapi-container -p 80:80 <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest
        EOF
